#
# Module manifest for module 'PSKnownFolders'
#
# Generated by: Woz
#
# Generated on: 03-13-2026
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'PSKnownFolders.dll'

# Version number of this module.
ModuleVersion = '2.5.0'

# Supported PSEditions
CompatiblePSEditions = @('Core', 'Desktop')

# ID used to uniquely identify this module
GUID = '9f8f181d-fa15-4abc-8fb2-ece8bdf3c122'

# Author of this module
Author = 'Woz'

# Company or vendor of this module
CompanyName = 'WozDev'

# Copyright statement for this module
Copyright = '(c) 2026 Woz. All rights reserved.'

# Description of the functionality provided by this module
Description = 'A set of cmdlets to manipulate the Known Folders of the Windows Shell.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
# DotNetFrameworkVersion = '4.8'

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = '2.0'

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = 'PSKnownFolders.dll'

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = @('PSKnownFolders.format.ps1xml')

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module
# FunctionsToExport = @()

# Cmdlets to export from this module
CmdletsToExport = @(
    'Get-PSKnownFolder',
    'Move-PSKnownFolder'
)

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module
AliasesToExport = @('Get-KnownFolder', 'Move-KnownFolder')

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = @('PSKnownFolders.dll','PSKnownFolders.format.ps1xml')

# Private data to pass to the module specified in RootModule/ModuleToProcess
# PrivateData = ''

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

