<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>PSKnownFolders</AssemblyName>
    <RootNamespace>WozDev.PSKnownFolders</RootNamespace>
    <ProduceReferenceAssembly>true</ProduceReferenceAssembly>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <SignAssembly>false</SignAssembly>
    <Title>WozDev.PSKnownFolders</Title>
    <Product>WozDev.PSKnownFolders</Product>
    <Authors>Woz</Authors>
    <Company>WozDev</Company>
    <Copyright>Copyright © 2026</Copyright>
    <NeutralLanguage>en-US</NeutralLanguage>
    <PackageOutputPath>bin\$(Configuration)\</PackageOutputPath>
    <!-- Define the project version -->
    <Version>2.5.0</Version>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DefineConstants>TRACE</DefineConstants>
    <DebugSymbols>false</DebugSymbols>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>

  <!-- Module content -->
  <ItemGroup>
    <Content Include="ModuleFiles\PSKnownFolders.format.ps1xml" />
    <Content Include="ModuleFiles\PSKnownFolders.psd1" />
  </ItemGroup>

  <!-- NuGet package references -->
  <ItemGroup>
    <PackageReference Include="PowerShellStandard.Library" Version="5.1.1">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <!-- Post-build target to copy files -->
  <Target Name="CopyModuleFiles" AfterTargets="Build">
    <PropertyGroup>
      <!-- Set destination folder using AssemblyName and Version -->
      <ModuleOutputPath>$(MSBuildThisFileDirectory)..\$(AssemblyName)_$(Version)\</ModuleOutputPath>
    </PropertyGroup>

    <!-- Ensure the output folder exists -->
    <MakeDir Directories="$(ModuleOutputPath)" />

    <!-- Copy DLL -->
    <Copy SourceFiles="$(OutputPath)$(AssemblyName).dll" DestinationFolder="$(ModuleOutputPath)" />
    <Copy SourceFiles="$(OutputPath)$(AssemblyName).pdb" DestinationFolder="$(ModuleOutputPath)" />
    <Copy SourceFiles="$(OutputPath)$(AssemblyName).xml" DestinationFolder="$(ModuleOutputPath)"
          Condition="Exists('$(OutputPath)$(AssemblyName).xml')" />

    <!-- Copy module files -->
    <Copy SourceFiles="@(Content)" DestinationFolder="$(ModuleOutputPath)" />
  </Target>

</Project>